version: "3.8"

services:
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - mynetwork
networks:
  mynetwork:
